echo "Cleaning repo first.."
rm -rf dist
rm -rf build
rm -rf benfordslaw.egg-info
rm -rf __pycache__
rm -rf .pytest_cache
rm -rf benfordslaw/__pycache__
rm -rf tests/__pycache__
rm -rf benfordslaw/utils/__pycache__
rm -rf .pylint.d
rm -rf benfordslaw/data/*.zip
rm -rf benfordslaw/data/*.csv
rm -rf *.js
rm -rf *.html
rm -rf *.css
rm -rf *.dot
rm -rf *.png
rm -rf .coverage*
rm -rf .pkl
